# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: "/assets/images/bio-photo.jpg"
# header:
#   overlay_image: "/assets/images/header_red.png"
  # overlay_filter: 0.3  # darkens the image a bit for contrast
  # caption: "Sheng — Tech Art & Game Development"
title: Sheng's Tech Art Portfolio
email:
description: >- # this means to ignore newlines until "baseurl:"
  Technical Artist Portfolio for Sheng Xu. Specializing in Unity, Unity3D, Autodesk Maya, Python, MEL, C#, HLSL, Shadergraph, VFX Graph.
  3D Artist, 3D Animator, Rigging, Game Developer, Programmer, Pipeline TD, VFX Artist, Shaders, Tools Developer.
twitter_username: username
github_username: swiney
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sheng Xu"
  avatar : "/assets/images/profile_pic_smiley.png"
  bio    : "Tech Artist / Game Developer / 3D Wiz"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-square-linkedin"
      url: "https://www.linkedin.com/in/swiney/"
    - label: "X (Formerly Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/swineyX"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/shengbean"
    - label: "Vimeo"
      icon: "fab fa-fw fa-vimeo-square"
      url: "https://vimeo.com/swiney"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-square-linkedin"
      url: "https://www.linkedin.com/in/swiney/"
    - label: "X (Formerly Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/swineyX"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/shengbean"
    - label: "Vimeo"
      icon: "fab fa-fw fa-vimeo-square"
      url: "https://vimeo.com/swiney"

defaults:
  # - scope:
  #     path: ""
  #   values:
  #     css:
  #       - /assets/css/main.css
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      show_date: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  projects:
    output: true
    permalink: /projects/:name/
